Register & Login page styles aligned
sametimesameplace/frontend pull request #4
Opened 2023-12-06 22:20 UTC by SteffenDCI

Tried to make it look better with my modest means.

2023-12-07 07:31 UTC, Termuellinator requested changes
Thanks for your work!
I think it looks quite nice already, though the font should be consistent between login and register (and not a dynamically imported google font).
Also, the Heading is not consistently aligned between login and register.

2023-12-07 07:31 UTC, Termuellinator commented on src/pages/login/Login.jsx
> +          <h1 className="App-title" style={{ fontFamily: 'IBM Plex mono', letterSpacing: '2px', fontSize: '2vw'}}>Become our newest member | Same Time Same Place</h1>
I think we should use the same font for login and registration

2023-12-07 07:31 UTC, Termuellinator commented on src/App.css
> +@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap');
I'm not the biggest fan of using google fonts to be honest, as this is know to be used by google to track users even if no other google services are used.

2023-12-07 08:55 UTC, merged

2023-12-08 13:58 UTC, SteffenDCI commented on src/App.css
> +@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap');
Thanks, I learned something new today,